### ISSUE TITLE
Typo of file name

### ISSUE THREAD

**Issue by notCoderJ** [TargetExpert/TESuit#3]
TEPostbu"li"d.cmake -> TEPostbu"il"d.cmake

**Comment by GabrielKim** [comment]
Thanks.
I'll change the file name.

**Comment by GabrielKim** [comment]
Apply now ebe1e19c66fda2c45a54d160147240581dac417f.

But, I haven't revise the code yet from 'TEInclude.cmake'.
I'll fix it in a few hours.

Thanks.

**Comment by GabrielKim** [comment]
Fixed.
